spring:
  name:
    food-backend
  datasource:
    url: jdbc:sqlite:food_service.db?busy_timeout=5000
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
      connection-timeout: 60000
      idle-timeout: 10000
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true